config/routes.rb
Shajarah::Application.routes.draw do
  resources :profiles
  resources :users
  resources :sessions
  root  :to => 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup', to: 'users#new', via: [:get, :post]
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get   '/login', :to => 'sessions#new', :as => :login 
  get   '/logout', :to => 'sessions#destroy', :as => :logout 
  get '/users', :to => 'users#index'
   get '/users/:id', :to => 'users#show'
  match '/authorize', to: 'static_pages#authorize', via: [:get, :post]

  

  

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :User
  validates :firstname, presence: true
   validates :relation, presence: true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]


  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new(profile_new_params)
   
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
 
  def create
    @profile = Profile.new(profile_params)
    respond_to do |format|
      unless Profile.find_by_user_id_and_relation(current_user.id, profile_params[:relation])
      if @profile.save
        format.html { redirect_to current_user, notice: 'Profile was successfully updated.' }
        format.json { render action: 'show', status: :created, location: User }
      else
        format.html { render action: 'new' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    else
        format.html { redirect_to current_user, notice: 'Profile already exists.' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
    end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update 
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to current_user, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to current_user }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:firstname, :fathername, :lastname, :relation, :user_id)
    end
    def profile_new_params
      params.permit(:firstname, :fathername, :lastname, :relation, :user_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<div class="row">
  <div class="span6 offset3">
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :fathername %><br>
    <%= f.text_field :fathername %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <% unless params['relation'] == "Self" %>
  <div class="field">
<%= f.select(:relation,options_for_select([['Father', 'Father'],['Mother', 'Mother'],['Brother', 'Brother'],['Sister', 'Sister'],['Son', 'Son'],['Daughter', 'Daughter'],['Spouse', 'Spouse']],2) )%>
</div>
<% else %>
  <div class="hidden">
<%= f.select(:relation,options_for_select([['Self', 'Self']],2) )%>
</div>
<% end %>
  <div class="hidden">
         <%= f.text_field :user_id %><br>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-large btn-primary"%>
  </div>
<% end %>
</div></div>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>


<%= render 'form' %>
<%= link_to 'Back', user_path(@profile.user_id) %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Fathername</th>
      <th>Lastname</th>
      <th>Relation</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.firstname %></td>
        <td><%= profile.fathername %></td>
        <td><%= profile.lastname %></td>
        <td><%= profile.relation %></td>
        <td><%= profile.user_id %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', user_path(@profile.user_id) %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @profile.firstname %>
</p>

<p>
  <strong>Fathername:</strong>
  <%= @profile.fathername %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @profile.lastname %>
</p>

<p>
  <strong>Relation:</strong>
  <%= @profile.relation %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |

<%= link_to 'Back', user_path(@profile.User) %>

<%= link_to 'Back', user_path(@profile.user_id) %>