config/routes.rb
Shajarah::Application.routes.draw do
  resources :profiles
  resources :users
  resources :sessions
  root  :to => 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup', to: 'users#new', via: [:get, :post]
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get   '/login', :to => 'sessions#new', :as => :login 
  get   '/logout', :to => 'sessions#destroy', :as => :logout 
  get '/users', :to => 'users#index'
   get '/users/:id', :to => 'users#show'
  match '/authorize', to: 'static_pages#authorize', via: [:get, :post]

  

  

end

app/models/user.rb
class User < ActiveRecord::Base
	 
	 	before_save {
	 	 if self.email
	 		self.email = email.downcase 
	 	end
    }
	 before_create :create_remember_token
has_many :profiles
 #has_secure_password

  validates :email,
                    format:     { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }

  validates :password, length: { minimum: 6 }
      [has_secure_password]
has_many :authorizations
def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end      
  
  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end



  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        flash[:success] = "Welcome to Shajarah!"
             sign_in(@user)
        format.html { redirect_to @user }
        format.json { render action: 'show', status: :created, location: @user }
      else 
        user1 = User.find_by_email(user_params[:email])
        authent = Authorization.find_by_user_id(user1.id)
        if authent 
        if user1.update(user_params)
           flash[:success] = user1.password
        end
        format.html { redirect_to "/auth/facebook/" }
        format.json { render action: 'show', location: @user }
        else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.profiles.each do |p|
      p.destroy
    end
    @user.authorizations.each do |a|
      a.destroy
    end
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<div class="row">
<div class="span6 offset3">
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
    <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
      <div class="field">
    <%= f.label :password_confirmation%><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
  </div>
<% end %>
</div></div>

app/views/users/edit.html.erb
<h1>Editing user Account</h1>


<%= render 'form' %>


<%= link_to 'Show', @user %> 

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Del', user,  method: :delete, data: { confirm: 'Are you sure?' }  %></td>
        <% if user == current_user %>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<p>
	<% if @user.email %>
<% authent1 = Authorization.find_by_user_id(@user.id)%>
	<% unless authent1 %>
  <%= gravatar(@user) %>
  <% else %>
  <% imgurl ='http://graph.facebook.com/' + authent1.uid + '/picture?type=normal' %>
  <%= image_tag(imgurl) %>
  <% end %>
  <strong>Email:</strong>
  <%= @user.email %> | <%= link_to 'Edit Account', edit_user_path(@user) %>
</p>
<%end %>
<% tester = false %>
<% @user.profiles.each do |p| %>
<% if p.relation == "Self" %>
<strong>Name: </strong>
<%=  p.firstname + " " + p.fathername + " " + p.lastname %> 
        <% if @user == current_user %>
        &nbsp;&nbsp;  ---    <%= link_to 'Edit', edit_profile_path(p) %>
        <% end %>
<% tester = true %>
<% end %>
<% end %>
<% if tester == false && @user == current_user %>
<%= link_to 'Complete Your Profile', new_profile_path(:user_id => @user.id, :relation => "Self") %>
<% end %>
<br/><br/>
<h4> Family:</h4>
<% @user.profiles.each do |p| %>
<% unless p.relation == "Self" %>
<strong> <%= p.relation + ": " %> </strong>
<%=p.firstname + " " + p.fathername + " " + p.lastname %>
<% if @user == current_user %>
 &nbsp;&nbsp; ---  <%= link_to 'Edit', edit_profile_path(p) %> | <%= link_to 'Delete', p, method: :delete, data: { confirm: 'Are you sure?' } %>
 <% end %><br/>
<% end %>
<% end %>
<% if @user == current_user %>
<br/>
<%= link_to 'Add Family Members', new_profile_path(:user_id => @user.id) %>
<br/> <br/> <br/> 
<div id="friends">
<p> <%= link_to 'Invite Your Friends', '#', :id => 'invite_fb_friends', class: "btn btn-large btn-primary facebook" %> </p>
<div id="fb-root"></div>
<script src="http://connect.facebook.net/en_US/all.js"></script>
<script>
$(function(){
  $('a#invite_fb_friends').click(function(){
    FB.init({
      appId: '786610081354504',
      cookie:false,
      status:true
    });
    FB.ui({method: 'apprequests', message: 'Try out this Shajarah App'});
  });
});</script>
</div>
<% end %>